src/shop/sale/Cart.vue
=> [feat] 장바구니 초기 컨셉

src/shop/auth/Login.vue
이슈번호 MF-2
내용
로그인 페이지 구성
스크린 샷
Closes MF-2
=> Kgj/auth/mf 2 로그인 페이지 html css 작성

src/router/index.js, src/shop/sale/Cart.vue, src/shop/subscription/Subscription.vue
=> [feat] 결제페이지 초기 컨셉

src/shop/sale/SaleDetail.vue
상품 상세보기 초기 컨셉 만듬
MF-6
상품 상세보기 페이지 구현
ㄴ 상품 구매페이지와 같은 페이지 
feat 
nav 바 안달음 밑에 더 추가해야함
Close MF-6
=> [feat] 상품 상세보기 초기 컨셉

src/router/index.js, src/shop/user/UserSubscription.vue
MF-10
사용자 구독 확인 초기 컨셉 만듬
router 에서 user/개인 구독 확인 안가는거
router에서 / 빼버림  그러니까 정상 작동
어떤 변경 사항이 있나요?
=> [feat] 사용자 구독 확인 초기 컨셉

src/shop/auth/SignupEnd.vue, src/shop/auth/SignupIdentify.vue, src/shop/auth/SignupInput.vue
MF-3
1. 본인인증 페이지
2. 회원정보 입력 페이지
3. 회원가입 완료 페이지 1->2->3으로 넘어가게 link 추가
기본 양식 작성, 1, 3은 단순해서 추후 변경가능성 높음
어떤 변경 사항이 있나요?
본인인증
개인정보 입력
회원가입 완료
=> [Feat] 회원가입 페이지 작성

src/shop/common/Home.vue, src/shop/common/component/Navbar.vue
#8 
MF-4
최상단 nav바에 장바구니 아이콘 추가 및 라우팅 설정, 카테고리 항목 라우팅 설정
어떤 변경 사항이 있나요?
=> [Feat] cart 아이콘 추가 및 라우팅 설정, 카테고리-> 상품 라우팅 설정 추가

src/admin/subscription/AdminSubscription.vue, src/router/index.js
MF-12
어드민 구독 관리 화면 구현 했습니다.
어떤 변경 사항이 있나요?
- [ x] 새로운 기능 추가
- [ x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
Close MF-12
=> [feat] 어드민 구독 관리 화면 구현

src/admin/product/AdminCategory.vue, src/router/index.js
#MF-14
상품 관리자 페이지 추가
어떤 변경 사항이 있나요?
테이블에서 컬럼명을 저렇게 두긴했는데 수정할 부분이 있으면 알려주세요
=> [Feat] 상품 관리 페이지 추가

src/admin/sale/AdminSaleRegister.vue
#MF-15
판매 등록 페이지 html css 추가
어떤 변경 사항이 있나요?
=> Kjg/mf 15 판매 등록 페이지 html css 작성

package-lock.json, package.json, src/main.js, src/shop/common/component/Footer.vue, src/shop/common/component/Navbar.vue
#8 mf-4
푸터 추가했습니다
어떤 변경 사항이 있나요?
푸터가 헤더처럼 화면에 꽉 차지 않는 것 수정해야합니다.
=> Kjg/mf 4 홈페이지 html css 작성

src/admin/product/AdminCategory.vue, src/admin/product/AdminProduct.vue
#MF-16
카테고리 관리 페이지 추가
어떤 변경 사항이 있나요?
티스토리의 카테고리 관리 탭처럼 해봤는데 수정하거나 보완해야 할 것 알려주세용
=> [Feat] 카테고리 관리 페이지 추가

src/admin/product/AdminProductRegister.vue
#MF-13
상품관리페이지 AdminProduct.vue로 이동 및 develop 브랜치에 상품 등록 페이지 사라졌던 것 다시 추가
어떤 변경 사항이 있나요?
상품관리페이지가 필요없다 했는데 일단은 adminProduct로 옮겨놨습니다.
=> [Chore] 상품관리페이지 AdminProduct.vue로 이동 및 상품등록페이지 추가

src/shop/common/component/Navbar.vue
#8 MF-4
헤더 수정 및 마이페이지 라우터 추가
어떤 변경 사항이 있나요?
=> [Feat]헤더네브바 수정 및 라우터 추가

src/shop/subscription/DeliveryTracking.vue
- 사용자 배송 조회 페이지 추가
- 패키지 추가
어떤 변경 사항이 있나요?
=> [Feat] 중간 발표 수정

src/shop/subscription/DeliveryTracking.vue
=> [Merge] 병합 수정

src/shop/common/component/Navbar.vue
#8 MF-4
메뉴바 코드를 개별 관리하는 것으로 수정
어떤 변경 사항이 있나요?
=> [Refactor]헤더 하단 바 코드 수정

src/App.vue, src/admin/common/AdminLayout.vue
=> [Fix] 디자인 수정

src/shop/sale/Cart.vue, src/shop/subscription/Subscription.vue
색 파랑색을 변경뒤 아이콘 x로 변경함
어떤 변경 사항이 있나요?
=> [fix] 색 수정, 아이콘 변경

src/router/index.js, src/shop/auth/SignupInput.vue, src/store/useUserStore.js
기본적인 것만 구현
정보를 받아서 넘김
앞으로 해야 할 것
태그 불러오기
태그 회원가입에 추가하기
휴대폰인증하기
아이디 중복 체크하기
어떤 변경 사항이 있나요?
=> [Feat] 회원가입 구현

src/router/index.js, src/shop/auth/Login.vue, src/shop/auth/SignupInput.vue, src/shop/common/component/Navbar.vue, src/store/useUserStore.js
MF-25, MF-24
로그인, 로그아웃 구현
어떤 변경 사항이 있나요?
=> Kgj/feat/mf 25 로그인 페이지 연동

src/admin/product/AdminProduct.vue, src/admin/product/ProductModal.vue, src/store/useProductStore.js
#MF-13
상품 관리 및 상품 등록 프론트 연동
어떤 변경 사항이 있나요?
=> Kjg/mf 13 상품 관리 페이지 html css 작성

src/admin/sale/AdminSaleRegister.vue, src/shop/common/Home.vue, src/store/useCategoryStore.js
#MF-4
홈페이지 프론트연동
어떤 변경 사항이 있나요?
=> [Feat] 홈페이지 프론트 연동

src/admin/product/AdminProduct.vue, src/admin/sale/AdminSaleRegister.vue, src/router/index.js, src/shop/common/Home.vue, src/shop/sale/SaleDetail.vue, src/shop/sale/SaleList.vue, src/store/useCategoryStore.js, src/store/useSaleStore.js
#MF-5
판매 상품 등록, 카테 고리별 판매 상품 조회 프론트 연동, 홈페이지 프론트 연동
어떤 변경 사항이 있나요?
=> Kjg/feat/mf 5 카테고리별 판매 목록 페이지 프론트연동

src/shop/sale/SaleList.vue
#MF-5
상품 목록 가로로 나오게 수정
어떤 변경 사항이 있나요?
=> [Style] 상품목록 가로로 나오게 수정

src/shop/sale/Cart.vue, src/shop/subscription/Subscription.vue
MF-40-장바구니-페이지-연동
장바구니 들어오면 값 불러오고
장바구니에서 결제로 넘어가면 결제창으로 데이터 값 넘겨줌
어떤 변경 사항이 있나요?
=> [feat] 장바구니 조회

src/shop/subscription/ReturnRequest.vue
반납하면 반납됩니다
MF-31-반납-신청-연동
반납하면 반납됩니다
어떤 변경 사항이 있나요?
=> [feat] 반납 기능 연동

src/shop/subscription/ReturnRequest.vue, src/shop/user/UserSubscription.vue
MF-34-사용자-전체-구독-조회-연동
슬라이스 기능 넣어서 밑으로 나옴 나중에 검색 기능 넣어도 되고 안 넣어도 되는데 프로튼 딴에서 이미 있는 데이터는 조회는 됌
어떤 변경 사항이 있나요?
=> Lee/feat/mf 34 사용자 전체 구독 조회 연동

src/admin/item/AdminItem.vue, src/admin/item/itemModal.vue, src/admin/product/AdminProduct.vue, src/admin/product/AdminProductRegister.vue, src/admin/product/ProductModal.vue, src/shop/sale/SaleList.vue, src/shop/sale/SaleSearch.vue, src/store/useProductStore.js, src/store/useSaleStore.js, vite.config.js
#MF-17
상품 검색 기능 추가
어떤 변경 사항이 있나요?
필터에 뭐가 추가되면 좋을까요?
=> Kjg/mf 17 상품 검색

src/router/index.js, src/shop/sale/SaleDetail.vue, src/shop/subscription/RepairRequest.vue, src/shop/subscription/ReturnRequest.vue, src/shop/user/UserSubscription.vue
수리 신청에 따른 프론트 변화
MF - 42 상품 분실 수리 
수리 신청 만들었는데 수리 신청만 했을 뿐 서비스로직 정확히 안됌 수리 신청만 해놨음
수리 신청에 따른 프론트 변화
어떤 변경 사항이 있나요?
=> [feat] 수리 신청

src/admin/item/AdminItemDetail.vue, src/admin/item/itemModal.vue, src/admin/sale/AdminSaleRegister.vue, src/router/index.js, src/shop/sale/SaleDetail.vue, src/shop/subscription/RepairRequest.vue, src/shop/subscription/ReturnRequest.vue, src/shop/user/UserSubscription.vue, src/store/useCategoryStore.js, src/store/useProductStore.js
#MF-15
판매상품 등록시 상품 코드로 등록, 
상품 관리 상세페이지에 들어가서 판매 상품으로 등록된 상품들을 확인할 수 있게 했음.
어떤 변경 사항이 있나요?
=> [Fix] 판매상품등록 방식 수정

src/admin/item/AdminItemDetail.vue, src/admin/item/itemModal.vue, src/admin/sale/AdminSaleRegister.vue, src/store/useCategoryStore.js, src/store/useProductStore.js
Reverts beyond-sw-camp/be12-fin-Gongcha1-MonthlyLIfe-FE#53
=> Revert "[Fix] 판매상품등록 방식 수정"

src/admin/item/AdminItemDetail.vue, src/admin/item/itemModal.vue, src/admin/sale/AdminSaleRegister.vue, src/router/index.js, src/store/useCategoryStore.js, src/store/useProductStore.js
#MF5 
상품관리페이지 이미지 보이게 및 상세페이지에 이미지 연동 추가
어떤 변경 사항이 있나요?
=> Kjg/fix/mf 15 판매등록페이지 카테고리 수정

src/admin/item/AdminItemDetail.vue, src/admin/item/ItemDetailModal.vue, src/admin/sale/AdminSaleRegister.vue, src/store/useSaleStore.js
MF-43
상품 수정, 삭제 프론트 연동 및 상품관리상세페이지 css 구현
어떤 변경 사항이 있나요?
=> [Feat] 판매 상품 수정,삭제기능 추가

package-lock.json, package.json, src/shop/common/Home.vue, src/shop/sale/SaleList.vue
#MF-4-홈페이지-css
홈페이지 배너 캐러셀 적용
어떤 변경 사항이 있나요?
pull 하고 돌리기 전에
npm install @splidejs/vue-splide
해주셔야 합니다
=> [Style] 홈페이지 배너 캐러셀 적용

src/Adminchat.vue, src/chat.vue, src/router/index.js, src/style.css
MF-44-채팅-기능
세션에서 id 값 가져와서 설정하는겁니다
관리자 로그인 안되어있으면 채팅 안보내집니다
시나리오 : 몇시~몇시까지만 채팅상담 운영한다하고 나머지 시간 챗봇이나 AI 운영
어떤 변경 사항이 있나요?
=> [feat] 채팅 기능 구현

src/admin/item/AdminItem.vue, src/admin/item/AdminItemDetail.vue, src/admin/item/itemModal.vue, src/shop/sale/SaleDetail.vue, src/store/useProductStore.js
#MF49-상품이미지추가 
상품 설명 이미지 추가 및 프론트연동
어떤 변경 사항이 있나요?
=> [Feat] 상품 설명 이미지 추가 및 프론트 연동

src/shop/auth/SignupInput.vue, src/shop/auth/component/SignupAddressInput.vue, src/store/useUserStore.js
=> Kgj/feat/mf 48 회원가입 검증

src/shop/user/UserDetail.vue, src/store/useUserStore.js
=> Kgj/feat/mf 45 유저 상세 페이지 연동

src/shop/sale/SaleDetail.vue, src/store/useSubcribeStore.js
#MF-26
판매 상품 상세페이지에서 장바구니, 구독 프론트 연동
어떤 변경 사항이 있나요?
=> [Feat] 장바구니, 결제 프론트 연동

src/store/useSaleStore.js
PUT/DELETE -> POST
어떤 변경 사항이 있나요?
=> [Fix]판매상품수정,삭제api 방식 수정

src/router/index.js, src/shop/common/component/Navbar.vue, src/shop/sale/Sale.vue, src/store/useSaleStore.js
#MF-52
전체 렌탈 상품 페이지 추가
어떤 변경 사항이 있나요?
=> [Feat]전체 렌탈 상품 페이지 추가

src/shop/sale/Sale.vue
=> [Style]배너 추가

src/router/index.js, src/shop/common/component/Navbar.vue, src/shop/sale/BestSale.vue, src/store/useSaleStore.js
#MF-54
BEST상품페이지 추가
어떤 변경 사항이 있나요?
=> [Feat]BEST상품 페이지 추가

src/router/index.js, src/shop/common/component/Navbar.vue, src/shop/sale/PackageSale.vue, src/store/useSaleStore.js
#MF-53
패키지특가 페이지 추가
어떤 변경 사항이 있나요?
=> [Feat]패키지특가 페이지 추가

src/admin/subscription/AdminDelivery.vue, src/router/index.js, src/shop/common/component/Footer.vue, src/shop/common/component/Navbar.vue, src/shop/etc/PrivacyPolicy.vue, src/shop/etc/PurchaseGuide.vue, src/shop/etc/Terms.vue, src/shop/subscription/Subscription.vue, src/store/useSubcribeStore.js
=> Kgj/fix/mf 54 구독 예외처리

src/shop/auth/SignupInput.vue, src/store/useUserStore.js, src/style.css
=> [Fix] 다크모드 오류 수정, 로그인 인증 추가

src/shop/common/ShopLayout.vue, src/shop/common/component/Navbar.vue, src/shop/sale/Sale.vue, src/store/useSaleStore.js
#MF-55
홈페이지 검색 기능 추가
어떤 변경 사항이 있나요?
=> [Feat]홈페이지 검색 기능 추가

src/shop/common/component/Navbar.vue, src/shop/sale/BestSale.vue, src/shop/sale/PackageSale.vue, src/shop/sale/Sale.vue
#MF-55
css 수정 및 구매가이드 라우팅 적용 
어떤 변경 사항이 있나요?
=> Kjg/mf 55 홈페이지검색

src/router/index.js, src/shop/subscription/DeliveryTracking.vue, src/shop/user/UserSubscription.vue
배송 정보 조회
배송 정보 조회
어떤 변경 사항이 있나요?
=> [feat] 배송 정보 조회

package-lock.json, package.json, src/shop/common/Home.vue, src/shop/common/Recommend.vue, src/store/useSaleStore.js
#MF-56
홈페이지에 카테리별 베스트 상품 추천 추가
어떤 변경 사항이 있나요?
=> [Feat]홈페이지 카테고리 별 상품 추천

src/shop/common/Home.vue, src/shop/common/NewArrival.vue, src/shop/common/Recommend.vue
#56,58
홈페이지 신상품 추천 추가 및 카테고리별 추천 css 수정
어떤 변경 사항이 있나요?
=> Kjg/feat/mf 58 신상품추천

src/shop/common/BestSales.vue, src/shop/common/Home.vue
#MF-58
Best상품추천 홈페이지에 추가
어떤 변경 사항이 있나요?
=> [Feat]Best상품추천 홈페이지에 추가

src/shop/common/Home.vue, src/shop/common/Weather.vue, src/store/useSaleStore.js
#MF-59
홈페이지 계절별 추천 추가
어떤 변경 사항이 있나요?
- [x 커밋 메시지 컨벤션에 맞게 작성했습니다.
=> [Feat]계절별 추천 추가

src/shop/common/Home.vue
=> [Style]배너 높이 수정

src/shop/common/Home.vue, src/style.css
=> [Style] 홈 배너 css 수정

src/admin/item/AdminItemDetail.vue, src/admin/item/ItemDetailModal.vue, src/shop/common/BestSales.vue, src/shop/common/Home.vue, src/shop/common/NewArrival.vue, src/shop/common/Recommend.vue, src/shop/common/Weather.vue, src/shop/sale/BestSale.vue, src/shop/sale/PackageSale.vue, src/shop/sale/Sale.vue, src/shop/sale/SaleDetail.vue, src/shop/sale/SaleList.vue, src/shop/sale/SaleSearch.vue, src/store/useSaleStore.js
#MF-58
목록불러오기개선
어떤 변경 사항이 있나요?
=> Kjg/feat/mf 58 목록불러오기개선

src/admin/payment/AdminPayment.vue, src/admin/product/AdminProduct.vue, src/admin/subscription/AdminDelivery.vue, src/admin/subscription/AdminReturnRequest.vue, src/admin/subscription/AdminSubscribe.vue, src/admin/user/AdminUser.vue
페이지 다나오는거 10개씩 나오도록 수정
어떤 변경 사항이 있나요?
=> [Fix] 페이지 여러개 나오는 거 수정

src/shop/common/ShopLayout.vue, src/shop/subscription/ReturnRequest.vue
=> [fix] 긴급 fix

src/shop/sale/PackageSale.vue, src/shop/sale/Sale.vue
=> [Refactor] 이미지 1개만 렌더링
